on:
  push:
    branches:
    - production
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Run reload through SSH
        run: "ssh -i ${{ secrets.SSH_PRIVATE_KEY }} dhs@direct.theneil.zone '/opt/neil-freelance/reload.sh'"
